### ISSUE TITLE
PDF backend issues with paint {}

### ISSUE THREAD

**Issue by jeremyz** [william8000/lout#4]
- with @Box : the PDF backend does not draw the black border like the PS backend does
- with @Tbl :  the PDF backend fails to meet the paint option

`replacing unknown @Case option col by black`

 
        @SysInclude { doc }
        @SysInclude { tbl }
        @SysInclude { xrgb }
        @Document
        //
        @Text @Begin
        @Box margin {1p} paint {lightgrey} Hello
        @Box margin {1p} paint {rgb .8 .8 .8} Hello
        @Box margin {1p} paint {@Xrgb lightgrey} Hello
        @Tbl
         {
           @Row
            format {@Cell paint {lightgrey} A}
            A {World}
           @Row
            format {@Cell paint {rgb .8 .8 .8} A}
            A {World}
           @Row
            format {@Cell paint {@Xrgb lightgrey} A}
            A {World}
         }
        @End @Text

**Comment by william8000** [comment]
The PDF output in lout is not fully implemented. For anything more than normal text, try making postscript and then using ghostscript ps2pdf to convert it to PDF.

**Comment by jeremyz** [comment]
I have been using ps2pdf for a while, sadly with my latest work, it fails.
Luckily I found an online converter that handles the job properly.
I would like to improve lout's PDF backend, any tip would be much appreciated.
Is the issue in the C code or in the lack of PDF support in lout package definitions ?
I tried to follow the white rabbit but ... he's too fast.
Is there a useful debug mode ?

**Comment by william8000** [comment]
If you have a postscript file where ps2pdf fails, you should submit it to the gs bugzilla at https://bugs.ghostscript.com/

I have been running lout output through ps2pdf daily for years and haven't had a problem since 2011. https://bugs.ghostscript.com/show_bug.cgi?id=692611

To have an idea of the size of the PDF issue, find the lout include files (in the include directory in the git repository or installed into a path like /usr/local/share/lout/lib/include), then search for 'PostScript' to find sections like

    def @SomeLoutCommand        {
        @BackEnd @Case { 
          PostScript @Yield { some postscript commands }
          PDF          @Yield {}
        }
    }

The @Yield command sends the postscript or pdf sequence to implement the command. All of the places that do nothing with PDF need to be filled in. Some of the C code for PDF support is in z24.c, z48.c, and z50.c.

I suspect that the lout commands with empty PDF in the includes would need more support in the C.

If you modify the makefile to set DEBUGGING = 1 (which sets -DDEBUG_ON=1), the lout -d option can enable debug flags as listed in externs.h. You can also add temporary debug with fprintf to stderr. 

If you make any improvements and send a patch or pull request and a test file, I'll apply them.

**Comment by jeremyz** [comment]
Thanks a lot, I've learn to use ps2pdf option `-sPAPERSIZE=a4`, that fixed my issue ;)
I found the bug, that was fun, I will try to improve whatever I can in the futur.
